language: python

sudo: false

python:
  - "3.5"

install:
  - "python setup.py install"
  - "pip install -r requirements.txt"
  - "pip install codecov"

script:
  - "coverage run tests/test_grammar.py"
  - "coverage run tests/test_compilers.py"
  - "coverage run tests/test_changer.py"

after_success:
  - "codecov"
