language: python
cache: pip

sudo: false

python:
  - "3.7"

install:
  - "python setup.py install"
  - "pip install codecov"

script:
  - "coverage run tests/test_parser.py"
  - "coverage run -a tests/test_changers.py"

after_success:
  - "codecov"
